GET http://localhost:8080/teacher

###

POST http://localhost:8080/teacher
Content-Type: application/json

[{
  "firstName": "Jan",
  "lastName": "Kowal",
  "age": 39,
  "email": "jan@example.pl",
  "subject": "informatyka"
},

  {
    "firstName": "Marian",
    "lastName": "Malinowski",
    "age": 45,
    "email": "marian@example.pl",
    "subject": "marketing"
  },

{
  "firstName": "Jerzy",
  "lastName": "Kamiński",
  "age": 47,
  "email": "jerzy@example.pl",
  "subject": "historia"
}]

###

DELETE http://localhost:8080/teacher/1