GET http://localhost:8080/teacher

###

GET http://localhost:8080/teacher/page/2

###

GET http://localhost:8080/teacher/sort/age

###

GET http://localhost:8080/teacher?firstName=Marian

###

GET http://localhost:8080/teacher?firstName=Jerzy&lastName=Kamiński

###

POST http://localhost:8080/teacher
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowal",
  "age": 18,
  "email": "jan@example.pl",
  "subject": "informatyka"
}

###

POST http://localhost:8080/teacher
Content-Type: application/json

  {
    "firstName": "Marian",
    "lastName": "Malinowski",
    "age": 45,
    "email": "marian@example.pl",
    "subject": "marketing"
  }

###

POST http://localhost:8080/teacher
Content-Type: application/json

{
  "firstName": "Jerzy",
  "lastName": "Kamiński",
  "age": 47,
  "email": "jerzy@example.pl",
  "subject": "historia"
}

###

DELETE http://localhost:8080/teacher/1